# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-12-11 18:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Travel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destination', models.CharField(max_length=255)),
                ('travel_start', models.DateTimeField()),
                ('travel_end', models.DateTimeField()),
                ('plan', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('add', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='added_by', to='login.User')),
                ('travels', models.ManyToManyField(related_name='travelled_by', to='login.User')),
            ],
        ),
    ]
