# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-12-11 21:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='travel',
            name='travel_end',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='travel',
            name='travel_start',
            field=models.DateField(),
        ),
    ]
